Просмотр общей информации о выбранном слое
hhru-school/segment-admin-panel pull request #12
Opened 2023-04-17 17:09 UTC by antonpigusov

Расширен DAO для слоев, добавлены DTO и mapper классы, спринговые аннотации заменены на @bean в конфигурации, добавлена ручка для получения информации о слое

2023-04-17 18:03 UTC, bannovdaniil requested changes
Хорошая, работа, но есть небольшие замечания.

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +    List<Layer> layerList = new ArrayList<>();
более логично эту переменную сместь ниже за ifn

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/basicInfo/LayerParentDto.java
с виду это полная копия LayerDto который уже лежит в master ветке. Может имеет смысл им воспользоваться , а не дублировать.

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/resource/LayerResource.java
> +    if (layerBasicInfoDto != null){
Кирилл рекомендовал, эту конструкции переписать с помощью Optional

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (layer != null){
Тут соответственно Optional
Кирилл также советовал такие мелочи не логгировать, посмотрит мой ПР для подробностей.

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/abstracts/LayerDao.java
> +  public List<Layer> getAllParents(Long id);
public в интерфейсах можно не указывать т.к. не несет никакой смысловой нагрузки.

2023-04-17 18:03 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/mapper/basicInfo/LayerParentMapper.java
это точная копия уже существующего LayerMapper
пользуемся принципом DRY

2023-04-17 20:48 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +    List<Layer> layerList = new ArrayList<>();
Согласен, поправил

2023-04-17 20:49 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/abstracts/LayerDao.java
> +  public List<Layer> getAllParents(Long id);
Да, ты прав, спасибо

2023-04-17 21:48 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/dto/basicInfo/LayerParentDto.java
Согласен, переборщил. Думал не передавать Group в статусе, но в целом нет разницы, объект действительно точно такой же

2023-04-17 21:49 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/mapper/basicInfo/LayerParentMapper.java
Да, ты прав, убрал

2023-04-17 22:13 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/resource/LayerResource.java
> +    if (layerBasicInfoDto != null){
Спасибо, что напомнил! Переписал

2023-04-17 22:13 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (layer != null){
Увидел, убрал логирование

2023-04-18 13:52 UTC, bannovdaniil approved these changes

2023-04-18 18:32 UTC, merged