Add questions views
hhru-school/segment-admin-panel pull request #18
Opened 2023-04-23 20:20 UTC by rubikkubika

Добавил бэкенд для страницы Вопросы(поля)

Добавил две ручки 

1. http://localhost:8080/questions/?layerId=7&searchString=
 Отдает дерево Вопрос-ответ-вопрос по ид слоя
Если параметр searchString пустой то отдает все дерево по слою

Если параметр String передан то фильтрует дерево  следующим образом:
Проверяет все объекты на наличие строки в title и description 
если находит то отдает весь вопрос целиком.
Для объектов в которых есть совпадение с searchString ставит признак searchedObject = true для последующей обработки на фронте

http://localhost:8080/questions/detail/?layerId=7&questionId=22
отдает дерево вопрос-ответ-вопрос по ид слоя и ид вопроса с дополнительными параметрами

Пример ответа для /questions/detail/?layerId=7&questionId=22 во вложении

[question_test_JSON.txt](https://github.com/hhru-school/segment-admin-panel/files/11304845/question_test_JSON.txt)

2023-04-24 16:53 UTC, bannovdaniil requested changes

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/abstracts/QuestionDao.java
> +  List<Question> findAllQuestionByLayerId(Long layerId);
перегруженный метод
findAll(Long layerId);
его предназначение видно из параметра.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/abstracts/QuestionActivatorLinkDao.java
> +  QuestionActivatorLink findQuestionActivatorLinkByLayerIdAndQuestionId(Long layerId, Long questionId);
перегруженный метод
findAll(Long layerId);
findBy(Long layerId, Long questionId);
его предназначение видно из параметра.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionActivatorLinkDaoImpl.java
> +        .setMaxResults(1)
не совсем понимаю логику доставать одну запись самую первую.
что нам это дает?
эту запись можно было бы получить из findAllQuestionActivatorLinkByLayerId без лишнего обращения к базе.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionDaoImpl.java
> +  public List<Question> findAllQuestionByLayerId(Long layerId) {
`List<Query> присутствует в Layer. Может более логично от туда его взять?`

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/mapper/AnswerMapper.java
> +    return answerDtoCollection
а может сюда прийти null?

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/AnswerDto.java
> +  private boolean isDefault;
а чем эта переменная будет отличаться от геттера?

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/QuestionDto.java
> +  private boolean required;
тут без is
почему там isDefault?

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/QuestionDto.java
> +  public boolean equals(Object o) {
этот equals может сравнить только сущность саму с собой т.к. id у всех сущностей всегда разный.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/questiondetailinfo/AnswerDtoForQuestionDetailInfo.java
> +  private boolean isDefault;
и тут is

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/questiondetailinfo/AnswerDtoForQuestionDetailInfo.java
> +  private boolean skipAtResult;
а тут нет is с чем это связанно?

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/questioninfopage/QuestionDtoForQuestionsInfoPage.java
> +  public boolean equals(Object o) {
По id сущности не сравниваются. id всегда разные.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    return id.equals(question.id);
id всегда разный на всю базу, нет повторяющихся.

Вопрос чем "водительские права" слоя 1 будет отличаться от "водительские права" слоя 2 ?

посмотри в data.sql погляди в базу данных.

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/resource/QuestionResource.java
> +  public Response getQuestionDtoInfoWithAnswers(@QueryParam("layerId") Long layerId,
layerId в прошлом просто Id

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/QuestionService.java
> +    List<Layer> selectedLayerWithParents = new ArrayList<>(List.of(optionalSelectedLayer.get()));
List.of тут точно надо?

2023-04-24 16:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/QuestionService.java
> +    Set<QuestionDtoForQuestionsInfoPage> questionDtoForQuestionsInfoPageSet = selectedLayerWithParents
объясни работу логику этого стрима, мне кажется он будет работать неправильно.

слои собираются от первого к последнему, у тебя они собираются в каком пороядке?

2023-04-24 17:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/abstracts/QuestionActivatorLinkDao.java
> +  QuestionActivatorLink findQuestionActivatorLinkByLayerIdAndQuestionId(Long layerId, Long questionId);
> перегруженный метод findAll(Long layerId); findBy(Long layerId, Long questionId); его предназначение видно из параметра.

А что значит твое замечание? Параметры в методе лишние? Я же должен как то передать ИД слоя  и вопроса которого ищу

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionDaoImpl.java
> +  public List<Question> findAllQuestionByLayerId(Long layerId) {
Этот метод ошибочно там, он нигде не используется. удалил

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionActivatorLinkDaoImpl.java
> +        .setMaxResults(1)
Этот сервис под другую ручку, когда смотрим детали одного вопроса. соответственно там findAll не используем.

Или ты имеешь ввиду, на страницу вопроса он не попадет пока не пройдет через загрузку всех вопросов? но тогда  нужно обработать если список пустой то тогда все равно идем в базу в противном случае берем из уже загруженного списка

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/AnswerDto.java
> +  private boolean isDefault;
default зарезервированное слово

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/QuestionDto.java
> +  private boolean required;
default зарезервированное слово

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/QuestionDto.java
> +  public boolean equals(Object o) {
Удалил. Я нигде это не использую

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/questiondetailinfo/AnswerDtoForQuestionDetailInfo.java
> +  private boolean skipAtResult;
default зарезервированнное слово

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/questiondetailinfo/AnswerDtoForQuestionDetailInfo.java
> +  private boolean isDefault;
default зарезервированнное слово

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/dto/questioninfopage/QuestionDtoForQuestionsInfoPage.java
> +  public boolean equals(Object o) {
Мне нужен был только hash code, equal сгенерировался автоматом. Поправил

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    return id.equals(question.id);
Автоматическая генерация кода. Удалил

2023-04-24 17:46 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/resource/QuestionResource.java
> +  public Response getQuestionDtoInfoWithAnswers(@QueryParam("layerId") Long layerId,
Поправил

2023-04-25 16:05 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionActivatorLinkDaoImpl.java
> +        .setMaxResults(1)
Метод был удален

2023-04-26 13:07 UTC, k-vasiliev approved these changes

2023-04-26 16:19 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/QuestionService.java
> +    List<Layer> selectedLayerWithParents = new ArrayList<>(List.of(optionalSelectedLayer.get()));
поправил

2023-04-26 18:16 UTC, bannovdaniil reviewed
Артем ты же говорил, что стримы переписываешь, с виду осталось все как и было.

2023-04-26 18:16 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/abstracts/QuestionActivatorLinkDao.java
> +  List<QuestionActivatorLink> findAllQuestionActivatorLinkByLayerId(Long layerId,ResumeField resumeField);
Имя Сущности можно убрать из имени метода и по Репозирорию и по возвращаемся параметру понятно что вернется

2023-04-26 18:16 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/dto/AnswerDto.java
> +  private boolean isDefault;
может такое имя будет лучше смотреться? answerDefault

2023-04-26 20:29 UTC, rubikkubika commented
> Артем ты же говорил, что стримы переписываешь, с виду осталось все как и было.

Насколько помню договорились не больше двух мап за стрим.

2023-04-26 20:36 UTC, bannovdaniil approved these changes

2023-04-28 17:03 UTC, merged