View segments
hhru-school/segment-admin-panel pull request #21
Opened 2023-04-25 08:06 UTC by antonpigusov

Сделано:
- ручка для получения всех сегментов для пространства слоя,
- ручка для получения информации о сегменте, его вопросах и полях, обязательности полей и вопросов, и видимости вопросов и полей для разных точек входа. Подсвечиваются статусами изменения: обязательность вопроса, изменение самого вопроса (если добавился ответ), видимости вопроса для разных точек входа.

2023-04-25 11:15 UTC, bannovdaniil reviewed
Привет, хороший код, приятно смотреть.

Добавил небольшие комментарии.

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionActivatorLinkDaoImpl.java
> +    for(Layer layer : layerSpace){
с виду Получилось, что бизнес логика появилась в репозитории.
производительности это не добавляет, а метод и непонятности прибавилось.

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/SegmentDaoImpl.java
> +    for (Layer layer : space) {
Цикл также не относится к репозиторию. findAll(Long layerId);
будет более понятно мне кажется.

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/resource/SegmentResource.java
> +  @Path("/{layerId}/{segmentId}")
Получается както не логично:
/segments/{layerId}/{segmentId}
наверное надо поменять местами и добавить слово
{segmentId}/layer/{layerId}

получится:
/segments/{segmentId}/layer/{layerId}
для большего понимания. Где какая цифра

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return Collections.EMPTY_LIST;
можно это заменить на List.of()

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +      Collections.reverse(layersInSpace);
размышлял над этим, можно не разворачивать лист, а при сборе смотреть если уже есть в списке (то следующий просто пропускаем.)

Если разворачиваем, то заменяем.

И так работать будет, но просто мысли на будущее.

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    Collections.sort(links,
про сортировку не сильно понял, ты выбираешь из базы по слоям, зачем еще одна сортировка?

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    Collections.sort(links,
на уровне слоя если то может в запрос SQL добавить ORDER BY

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return !currentLink.isQuestionRequired() == parentLink.get().isQuestionRequired();
currentLink.isQuestionRequired() != parentLink.get().isQuestionRequired()

2023-04-25 11:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return !currentLink.getQuestion().equals(parentLink.get().getQuestion());
а в getQuestion 
какой equals прописан?, не увидел

2023-04-25 22:08 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/resource/SegmentResource.java
> +  @Path("/{layerId}/{segmentId}")
Согласен, неинформативно. Понравилось решение через @QueryParam. Тогда ручки будут такие: localhost:8080/segments?layerId=5 и  localhost:8080/segments/details?layerId=5&segmentId=5

2023-04-25 22:39 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/impl/QuestionActivatorLinkDaoImpl.java
> +    for(Layer layer : layerSpace){
Да, ты прав. Убрал логику из репозитория

2023-04-25 22:40 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/impl/SegmentDaoImpl.java
> +    for (Layer layer : space) {
И тут тоже вынес в сервис. Как ты считаешь, getAllParents из LayerDao стоит вынести в сервис таким же образом?

2023-04-25 22:43 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return Collections.EMPTY_LIST;
Мне как-то привычнее видеть Collections.EMPTY_LIST. Почитал про разницу, она заключается в основном на реакцию, когда хотим проверить contains(null), List.of() в этом случае выкинет исключение, а Collections.EMPTY_LIST вернет false. Еще Collections.EMPTY_LIST сериализуется. Нам эта разница ничего не дает, кроме как List.of() короче в написании

2023-04-25 22:53 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    Collections.sort(links,
Да, ты прав, Даниил. Я перед этим уже получаю список слоев в пространстве, который отсортирован по хронологии слоев, а для них получаю все линки, так что эта сортировка тут действительно лишняя

2023-04-25 23:03 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return !currentLink.getQuestion().equals(parentLink.get().getQuestion());
Не совсем понял вопрос. currentLink.getQuestion() вернет мне Question из текущего линка, а parentLink.get().getQuestion() вернет Question из родительского линка. equals для Question я не переопределял, так что если в вопрос в текущем слое добавился ответ, либо вопрос изменился каким-то образом, то equals просто вернет мне false, чтобы я мог сам вопрос подсветить на предмет изменений

2023-04-26 06:19 UTC, bannovdaniil requested changes

2023-04-26 06:19 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/mapper/viewsegments/SegmentViewEntryPointMapper.java
> +        link.getEntrypoint().getTitle(),
в этом месте может произойти NPE. хотя для линков всегда вроде все есть..

2023-04-26 06:19 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +//  private List<Layer> getAllParents(Layer layer) {
комментарии в коде это очень плохо.
YAGNI

2023-04-26 06:19 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/SegmentService.java
> +    return !currentLink.getQuestion().equals(parentLink.get().getQuestion());
если equals не переопределен , объекты у тебя всегда будут разные, какой тогда смысл этой проверки? ты пытаешься найти тотже объект в другом слое но этого не случится, т.к. id всегда разные.

2023-04-26 07:43 UTC, bannovdaniil approved these changes

2023-04-26 12:59 UTC, rubikkubika commented on src/main/resources/hibernate-dev.properties
> +hibernate.connection.password=37Wzbuk7z
пароль)

2023-04-26 13:04 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/abstracts/SegmentDao.java
> +  List<Segment> findAll(Long layerId);
А метод же вроде есть в базовом?

2023-04-28 13:21 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/abstracts/SegmentDao.java
> +  List<Segment> findAll(Long layerId);
В базовом findAll без параметров, т.е. найдет вообще все сегменты. А этот метод находит сегменты, созданные в выбранном слое

2023-04-28 21:55 UTC, merged