Dev new data model
hhru-school/segment-admin-panel pull request #28
Opened 2023-05-13 23:00 UTC by antonpigusov

Доработаны сущности, добавлены новые в соответствии с новой моделью данных.
Все куски кода, которые стали неактуальны, вырезаны. Где-то оставил в методах return null, часть методов и классов удалил, т.к. изменился или тип аргумента, или возвращаемый тип, или сам класс перестал существовать.
В тестовых данных оставил только слои. 
Сейчас работают ручки на просмотр всех слоев и на просмотр информации о конкретном слое.

2023-05-14 18:41 UTC, bannovdaniil requested changes
немного проверил, Мало времени, что успел, завтра продолжу.

2023-05-14 18:41 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +import javax.persistence.*;
про * не помню, это же не проблема?

2023-05-14 18:41 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +public class Application implements Serializable {
а зачем он Serializable?

2023-05-14 18:41 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +  Set<Screen> screens;
Set точно не надо тут делать, это обозначает что надо в screens переопределять equals и hashcode. и какие то еще нюансы есть у Set в hibernate сущностях.

2023-05-14 18:41 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +  @ManyToMany(cascade = {CascadeType.ALL})
Тоесть получается если удалить Application удалится все скрины?

2023-05-14 18:41 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  @Column(name = "platform", nullable = false)
платформа может быть null?

2023-05-15 06:04 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +import javax.persistence.*;
Нет, так быть не должно, пропустил, спасибо

2023-05-15 06:46 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +public class Application implements Serializable {
Изучил. Получается, нет смысла. Это бы пригодилось, если бы по сети мы передавали бы саму сущность, а не DTO

2023-05-15 09:15 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +  @ManyToMany(cascade = {CascadeType.ALL})
Согласен, непорядок

2023-05-15 09:17 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  @Column(name = "platform", nullable = false)
Мне кажется, нет. Иначе получится, что версия приложения не привязана к платформе, а такого вроде бы не может быть

2023-05-15 13:35 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  @Column(name = "platform", nullable = false)
думал про unique а написал, про null вот я кадр :)

2023-05-15 14:01 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  @Column(name = "platform", nullable = false)
Unique по идее тоже не должна быть, ведь платформа это WEB, Android, IOS и т.д., т.е. они повторяются

2023-05-15 17:51 UTC, bannovdaniil requested changes
Привет, класс, все почти идеально.

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
>    private boolean isDefault;
предлагаю переименовать в defaultAnswer

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +public class Application {
![image](https://github.com/hhru-school/segment-admin-panel/assets/96119195/2bb7a821-b519-4386-82da-92a0ccbf53bc)

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  @Column(name = "platform", nullable = false)
Извини, точно, не туда смотрю , это же platform_id, но вчера вечером прочему то думал, что это про platform

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +public class Screen {
![image](https://github.com/hhru-school/segment-admin-panel/assets/96119195/c7a52df0-6502-4d3f-83ed-f3b990c12320)

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +  Set<Application> applications;
Set это плохо надо List
не нашел ничего толкового
https://javatutor.net/articles/hibernate-sets-bags-etc
set в любом случаи работает медленее List а уникальность, нас тут мало интересует.

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  private String platform;
Это enum ANDROID, IOS, WEB

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
>    private List<Long> possibleAnswerIdList;
предлагаю убрать от сюда, Id
possibleAnswerIdList => possibleAnswerList
читается легче, а по типу вроде и так понятно что там ID

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private ResumeField type;
Тут поменялся тип Поля раньше это було буллеан а сейчас string
посмотри пожалуйста этот enum ResumeField => в нем надо внести измениеня.

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/ScreenQuestionLink.java
> +  private QuestionVisibilityType questionVisibility;
это не замечание, А просто пока вспомнил, записал для себя, надо уточнить по enum QuestionVisibilityType, на последнем митапе у Ильи на фремах было больше типов видимости.

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +  private List<Long> platformsList;
Предлагаю переименовать в platformsList => platformList

2023-05-15 17:51 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +  @ManyToMany(mappedBy = "screens")
может я туплю, а почему он мапится на screens?

2023-05-15 17:54 UTC, bannovdaniil reviewed
вроде не критично, есть небольшая просьба, Антон можешь в сущностях поля расположить в порядке как на схеме? кроме ID, а то реально задрался их сверять :)))

2023-05-15 21:51 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Application.java
> +public class Application {
Странно, у меня почему-то не подсветило тут. Добавил, спасибо!

2023-05-15 22:21 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +  Set<Application> applications;
Действительно, тут проморгал, спасибо!

2023-05-15 22:32 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private ResumeField type;
Не доглядел! Спасибо, Даниил!

2023-05-15 23:25 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +  @ManyToMany(mappedBy = "screens")
Это хороший вопрос на самом деле. Получается, что при ManyToMany одна сущность будет owner-ом https://stackoverflow.com/questions/14111607/manytomanymappedby-foo. Причем owner как правило - это первая сущность, указанная в названии связующей таблицы, т.е. в нашем случае Screen. Тогда описать связь нужно действительно наоборот. Тем более, что у нас может быть несколько экранов для одной версии приложения

2023-05-15 23:54 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Platform.java
> +  private String platform;
Да, я совсем забыл, спасибо!

2023-05-16 10:07 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/model/entity/Screen.java
> +  @ManyToMany(mappedBy = "screens")
Хороший вопрос, вроде бы разобрался, mappedBy лучше делать в Application классе

2023-05-16 12:57 UTC, bannovdaniil approved these changes

2023-05-16 12:59 UTC, merged