Добавил тестовые данные
hhru-school/segment-admin-panel pull request #29
Opened 2023-05-17 14:51 UTC by rubikkubika

Добавил тестовые данные 3 слоя

2023-05-17 19:41 UTC, antonpigusov commented on src/main/resources/data.sql
> +INSERT INTO platforms (platform,application_version)
Насколько помню, говорили, что WEB версий не имеет, наверно и тут как-то стоит отразить

2023-05-17 19:42 UTC, antonpigusov commented on src/main/resources/data.sql
> +              ('IOS','1'), --2
Мб докапываюсь, но было бы круто версии видеть не 1 или 2, а что-то вроде 1.4, 2.5 и т.д.

2023-05-17 19:44 UTC, antonpigusov commented on src/main/resources/data.sql
> +       ('Android', 'Экраны для платформы Android','{6,3}','ACTIVE');  --4
Скорее всего для фронта еще понадобится экран с состоянием ARCHIVE

2023-05-17 20:06 UTC, antonpigusov commented on src/main/resources/data.sql
> +       ('Узкоспециализированные вопросы', 'Заполнение ответов на спецаильные вопросы','DYNAMIC','ACTIVE');  --4
Скорее всего для фронта еще понадобится экран с состоянием ARCHIVE

2023-05-17 20:06 UTC, antonpigusov commented on src/main/resources/data.sql
> +INSERT INTO segments (layer_id,parent_segment_id,old_segment_id,title,description,role,tag)
Вынесли сегменты из слоев, посмотри свежий ПР Даниила (можно будет добавление всех строк в segments вынести тоже наверх, как справочник)

2023-05-17 20:06 UTC, antonpigusov commented on src/main/resources/data.sql
> +       (2,NULL,2,1,3,3,3,1,'HIDE_PREFILLED'), -- 15
Еще появилась новая видимость, SHOW_PREFILLED, было бы круто ее тоже где-то отразить

2023-05-17 20:06 UTC, antonpigusov commented on src/main/resources/data.sql
> +INSERT INTO question_required_links (layer_id,old_id,segment_id,application_id,question_id,question_required)
Будет очень здорово, если добавишь 1-2 линка для каждой таблицы с линками, где будет видно, что что-то изменилось, т.е. old_id != NULL

2023-05-18 07:09 UTC, bannovdaniil commented on src/main/resources/data.sql
> +INSERT INTO segments (layer_id,parent_segment_id,old_segment_id,title,description,role,tag)
Поддерживаю, на последнем митапе, обсудили вынос сегментов из слоев. В таблице сегменты, появились изменения.

2023-05-18 07:13 UTC, bannovdaniil commented on src/main/resources/data.sql
> +       (3,NULL,3,2,2,3,1,1,'SHOW'), --
предлагаю в этой таблице сделать большее разнообразие состояний.

SHOW, HIDE, SHOW_PREFILLED, HIDE_PREFILLED

2023-05-18 07:23 UTC, bannovdaniil requested changes
Большая работа, много данных, будет на чем тестировать. :)

2023-05-18 07:23 UTC, bannovdaniil commented on src/main/resources/data.sql
> +INSERT INTO segment_application_screen_links (layer_id,old_id,segment_id,entrypoint_id,application_id,screen_id,screen_position)
посмотрел все segment_application_screen_links
не увидел чтобы old_id где-то имел значение, как измененные данные, везде NULL добавь пожалуйста, в каком-то из слоёв, видимость изменения позиций.

2023-05-18 07:23 UTC, bannovdaniil commented on src/main/resources/data.sql
> +INSERT INTO screen_question_links (layer_id,old_id,segment_id,entrypoint_id,application_id,screen_id,question_id,question_position,question_visibility)
screen_question_links , также не где не используется значения для old_id

2023-05-19 10:59 UTC, closed without merging