Настройка docker
hhru-school/segment-admin-panel pull request #3
Opened 2023-04-03 22:31 UTC by antonpigusov

Настройка docker и docker compose для backend-сервиса.
В docker compose входит образ для 2 контейнеров: backend-сервиса и PostgreSQL.
Для корректной сборки .jar файла добавлен плагин spring-boot-maven-plugin.
Для проверки работоспособности добавлена тестовая ручка.
Описание взаимодействия с docker в файле README.md

2023-04-04 04:25 UTC, bannovdaniil commented on .env
> +POSTGRES_HOST_PORT=6580
А почему 8081 а не 8080? У фронтов вроде на 8080 идёт привязка

2023-04-04 04:28 UTC, bannovdaniil commented on src/main/resources/application.properties
> +server.port=8081
Попробуй вставить порт через environment

2023-04-04 04:30 UTC, bannovdaniil reviewed
Хорошая работа, 👍 и есть тест и сборка прямо в контейнере.
Маленький вопрос и одно предложение в комментариях.

2023-04-04 05:44 UTC, bannovdaniil requested changes
Добрался до компьютера, Все почти собралось, maven зависимости качались, и тесты прошло, но на этапе копирования jar оказалось что его нет.

2023-04-04 05:44 UTC, bannovdaniil commented on Dockerfile
> +COPY target/*.jar segment-admin.jar
Добрался до компьютера.

![image](https://user-images.githubusercontent.com/96119195/229697898-a685377b-309c-4d93-a884-8494267f7532.png)

2023-04-04 05:44 UTC, bannovdaniil commented on README.md
> +    docker compose build
Все что до это написано, можно смело убрать, оставить только компоуз, он все соберет сам.

docker-compose build

2023-04-04 05:44 UTC, bannovdaniil commented on README.md
> +    docker compose up
docker-compose up

2023-04-04 05:44 UTC, bannovdaniil commented on README.md
> +    docker compose stop
docker-compose stop

тире везде пропущено

2023-04-04 11:06 UTC, antonpigusov commented on .env
> +POSTGRES_HOST_PORT=6580
Договорились с Бекеном, сделал 8080

2023-04-04 11:11 UTC, antonpigusov commented on README.md
> +    docker compose build
Работает и с "-", и без. В оф доке без тире https://docs.docker.com/engine/reference/commandline/compose/

2023-04-04 11:12 UTC, antonpigusov commented on src/main/resources/application.properties
> +server.port=8080
Не придумал, как использовать тут переменную окружения. Нашел 2 варианта: 1 - добавить в системные переменные (чего делать не захотелось), и 2 - сделать профили для spring boot (посчитал, что это излишне, пока не стал делать)

2023-04-04 13:54 UTC, bannovdaniil commented on README.md
> +Порты по умолчанию: 8081 - для backend-сервиса, 6580 - для PostgreSQL.
8080

2023-04-04 13:59 UTC, bannovdaniil requested changes
Отличная работа! все запустилось.
в 2х местах еще осталось "8081"
docker-compose это скорее дело привычки.

надо бы добавить в properties настройку Postgre SQL, чтобы можно было начинать работать и у всех было однообразно.

2023-04-04 13:59 UTC, bannovdaniil commented on src/main/resources/application.properties
> +server.port=8080
по хорошему надо добавить настройки для PostGre сразу в properties.

2023-04-09 08:39 UTC, bannovdaniil approved these changes
Отличная работа, все работает как часы !

2023-04-09 16:15 UTC, bannovdaniil requested changes

2023-04-09 16:15 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/JerseiAppConfig.java
имя надо переименовать на JerseyAppConfig.java

2023-04-11 21:08 UTC, rubikkubika approved these changes

2023-04-11 21:08 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/configuration/HibernateConfig.java
> +}
Предлагаю изменить конфиг через LocalSessionFactoryBean  пример можно взять отсюда https://github.com/hhru-school/hh-coins/blob/develop/backend/src/main/java/ru/hh/coins/config/HibernateConfig.java

2023-04-11 21:08 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/SegmentApplication.java
>    }
предлагаю не засорять главный класс тестовыми операциями

2023-04-11 21:08 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/TestDao.java
> +  }
Предлагаю  не засорять тестовыми сущностями. Если нужные тестовые то можно их создать но не добавлять в гит, тогда они будут только у тебя локально

2023-04-11 21:08 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/SegmentApplication.java
>    }
@antonpigusov  

Вот это может тоже удалим ? ConfigurableApplicationContext context =

2023-04-11 23:06 UTC, bannovdaniil approved these changes

2023-04-11 23:10 UTC, merged