Add entity
hhru-school/segment-admin-panel pull request #4
Opened 2023-04-10 07:55 UTC by rubikkubika

Добавил основные сущности.

Схем DB  сгенерированная Hibernate выглядит так 

![db_schema](https://user-images.githubusercontent.com/98896050/230855223-f527f186-5b5f-4d72-8764-567b93928803.png)

2023-04-10 16:24 UTC, bannovdaniil requested changes
Хорошая работа, но есть что исправить, схему не покрывает. Видимо нет понимания как все должно работать, если есть необходимость переслушай митапы или давай проговорим это отдельно.
 подробности в комментариях.

2023-04-10 16:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Layer.java
Получив сущность Layer у нас должны оказаться на руках все сущности которые от него зависят. Сейчас этого нет.
не хватает OneToMany к всем сущностям.

2023-04-10 16:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
> +  private String Type;
нет сущности enam для этого поля

2023-04-10 16:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private String type;
нет поля enam для этого поля

2023-04-10 16:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/History.java
> +  private String type;
enam DELETE, CREATE, UPDATE

2023-04-10 16:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +  @OneToOne(fetch = FetchType.LAZY)
а с почему тут OneToOne?

2023-04-10 16:35 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +  @OneToOne(fetch = FetchType.LAZY)
А почему нет? Под каждый вопрос создаем свой activator link, который содержит всю информацию о других сущностях(вопрос, сегмент, слой)

2023-04-11 07:33 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Layer.java
добавил

2023-04-11 07:33 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +  private boolean questionRequired;
добавил

2023-04-11 07:33 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
> +  private String Type;
добавил

2023-04-11 07:33 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private String type;
добавил

2023-04-11 07:33 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/History.java
> +  private String type;
добавил

2023-04-11 07:34 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +  @OneToOne(fetch = FetchType.LAZY)
Изменил на One to Many

2023-04-11 14:18 UTC, bannovdaniil requested changes
в Links enum так и не появился, имена переменных не соответствуют именам в БД, или нет @Column у таких полей.

2023-04-12 04:28 UTC, bannovdaniil requested changes

2023-04-12 04:28 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
Layer убрали это хорошо теперь нет n+1, но как мне теперь понять это этот ответ из лейера №2 , а не из №3.?
 Это надо для сравнения.

2023-04-12 08:30 UTC, sabkaryan commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  }
хм. я думал мы вопросы будем доставать через EntryPoint через связь с QuestionActivatorLinks
и в QuestionActivatorLinks останутся Question и Answer

2023-04-12 09:45 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  }
![Screenshot_2023-04-12-12-43-51-426_com.mattermost.rn-edit.jpg](https://user-images.githubusercontent.com/98896050/231420598-29f98dfc-3c5d-4bb4-a682-6fa9690663e4.jpg)
Ответы на схеме с Линкс не связаны

2023-04-12 10:10 UTC, sabkaryan commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  }
понял. А как вопросы с ответами связаны? Я вижу в слое список вопросов и список ответов
нам нужно будет строить такую штуку
<img width="945" alt="Screenshot 2023-04-12 at 13 08 44" src="https://user-images.githubusercontent.com/1016430/231426772-61d52884-e952-4917-bba8-2eebc75928e6.png">
Вопрос -> список ответов на него

2023-04-12 17:18 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  }
> понял. А как вопросы с ответами связаны? Я вижу в слое список вопросов и список ответов нам нужно будет строить такую штуку <img alt="Screenshot 2023-04-12 at 13 08 44" width="945" src="https://user-images.githubusercontent.com/1016430/231426772-61d52884-e952-4917-bba8-2eebc75928e6.png"> Вопрос -> список ответов на него

@sabkaryan , сможешь нарисовать в каком виде представление будет удобно, нарисую DTO вернется ровно, как нужно.

2023-04-12 17:56 UTC, sabkaryan commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  }
тогда вопросов нет)

2023-04-13 13:24 UTC, bannovdaniil requested changes
Указал подробно, что исправить, спасибо за хорошую работу, увлекательно провел час времени.

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
> +
@Column(name = "layer_id")
  private Long layerId;

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Entrypoint.java
> +
@Column(name = "layer_id")
  private Long layerId;

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Entrypoint.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
В этой зависимости тут нет смысла.

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Layer.java
> +
@OneToMany(fetch = FetchType.LAZY)
  @JoinColumn(name = "queston_id")
  private List<Question> questionList;
  @OneToMany(fetch = FetchType.LAZY)
  @JoinColumn(name = "entrypoint_id")
  private List<Entrypoint> entrypointList;
  @OneToMany(fetch = FetchType.LAZY)
  @JoinColumn(name = "segment_id")
  private List<Segment> segmentList;

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private boolean requiredType;
private boolean requiredType; 
  почему выбрано такое название переменной?

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    return questionActivatorLinksList;
Этот геттер для какого поля?

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    this.questionActivatorLinksList = questionActivatorLinksList;
этот сеттер для какого поля?

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
а зачем поля в перемешку с Геттерами и Сеттерами?
эта связь избыточна.

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +
не хватает entrypoint_id

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
этой сущности необходимо добавить Equals и HashCode т.к. она единственная не статическая и постоянно меняет свое состояние.

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<Long> roleIdList;
roleList может более логично?

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<String> tagArrayList;
Это список Массивов Тегов, странное название переменной.
это просто список тегов, разве нет?

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
тут эта связь избыточна.

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +
@Column(name = "layer_id")
  private Long layerId;

2023-04-13 13:24 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/enums/QuestionType.java
> +  MULTI_SELECT
Не хватает еще одного типа, говорили про него на последнем митапе.

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/enums/QuestionType.java
> +  MULTI_SELECT
пересмотрел митап, там говорил что Custom не будет, только Сингл и Мультиселект

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<String> tagArrayList;
поправил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<Long> roleIdList;
поправил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
> +
добавил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private boolean requiredType;
поправил на просто required

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
удалил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
удалил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    this.questionActivatorLinksList = questionActivatorLinksList;
удалил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Question.java
> +    return questionActivatorLinksList;
удалил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Entrypoint.java
> +  private List<QuestionActivatorLinks> questionActivatorLinksList;
удалил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Answer.java
> +
добавил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Entrypoint.java
> +
добавил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Segment.java
> +
добавил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/QuestionActivatorLinks.java
добавил

2023-04-13 16:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/model/entity/Layer.java
> +
Добавил

2023-04-14 03:34 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/model/enums/QuestionType.java
> +  MULTI_SELECT
> 

а как ты его смог пересмотреть запись еще не доступна? третье значение NONE

2023-04-14 03:35 UTC, bannovdaniil approved these changes

2023-04-14 07:47 UTC, closed without merging