Добавил ручку для проведения мерджа и поиска конфликтов
hhru-school/segment-admin-panel pull request #58
Opened 2023-06-08 14:11 UTC by rubikkubika

Ручка  layers/{layerId}/merge

Переиспользовал механизм ранее написанный в SegmentsView

1. Если родительский слой layerId  == последнему стабильному, то меняем статус layerId на Stable, отправляем сообщение в ответе что статус поменяли

2. Если родительский слой layerId  != последнему стабильному, то:

-  Меняем родителя layerId на последний стабильный

- Ищем конфликты относительно родителя, на:
Изменился статус существующего сегмента
Изменился порядок экранов в существующих сегментах
Изменился порядок полей в существующих сегментах
Изменилась видимость полей в существующих сегментах

- Если конфликтов нет, то то меняем статус layerId на Stable, отправляем сообщение в ответе что статус поменяли

- Если есть конфликты то отправляем сообщением с перечнем конфликтов

2023-06-08 22:06 UTC, bannovdaniil requested changes
Привет, посмотрел только на синтаксис, 
conflictMessages - это надо точно обсудить с Бекеном т.к. помню конфлиты ему совсем иначе отдавал.
по логике скорее всего подскажет Антон попроси его тоже сделать ревью

из того что бросилось в глаза, а значит и алгоритм точно не рабочий нигде не увидел LayerStateType.CONFLICT

2023-06-08 22:06 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +             WHERE l.state IN :layerStatus
тут вместо IN возможно лучше использовать просто =
 и добавить LIMIT 1

2023-06-08 22:06 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      return List.of(List.of("Такого слоя не существует.  Последний стабильный слой имеет id" + lastStableLayer.getId()));
Очень странная конструкция, надо бросить исключение. HttpNotFound(message)  id не желательно указывать, в сообщениях об ошибках, в логах надо, а то что получает фронт, может помочь только хакеру.

2023-06-08 22:06 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      return List.of(List.of("Тестовый слой унаследован от последнего стабильного слоя. [Сделал тестовый слой с Id" + mergingLayer.getId() + " стабильным]"));
List => List очень странно смотрится.

2023-06-08 22:06 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  public List<List<String>> mergeLayerWithParent(Long layerId) {
List<List<
возможно надо сделать правильную Dto

2023-06-08 22:06 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (Objects.equals(mergingLayer.getParent().getId(), lastStableLayer.getId())) {
вероятнее всего, где-то тут надо сделать проверку на то что слой который на мердж НЕ Stable.

2023-06-09 13:56 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +             WHERE l.state IN :layerStatus
Еще чтобы явное приведение не использовать, можно вторым аргументом в createQuery добавить Layer.class

2023-06-09 13:56 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    List<List<String>> conflictMessages = new ArrayList<>();
Эти 2 массива можно создавать после 2 условия, раньше они не используются

2023-06-09 14:48 UTC, antonpigusov commented
Напишу тут, чего я не увидел / не понял (может быть где-то не прав):
1. Возможно стоит обсудить с Бекеном, что именно отдавать ему на фронт. Нужны ли ему сами различия? Возможно нет, потому что следующим шагом по алгоритму все равно будет создание нового слоя, в котором будут отражены конфликты. Мб отдавать просто некое сообщение типа "Автомерж невозможен, делай все руками"? Если так, то тогда разницу можно искать до первого дифа и сразу слать ответ. Иначе получается двойная работа, сейчас нашли все дифы, и на следующем шаге опять будем их искать.
2. Не проверяется изменение обязательности полей, это поле isChanged в fields. Это поле есть всегда. 
3. Не проверяется изменение состояния самого поля (активное или удаленное) в сегменте. Я на просмотр шлю только текущее состояние поля (так договорились с Бекеном), но в SegmentService есть метод getActiveQuestions, который возможно поможет найти все активные вопросы для текущего и родительского слоя и уже найти дифы.
4. Не проверяется состояние экрана, имеется в виду активный он или нет.

2023-06-09 18:32 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +             WHERE l.state IN :layerStatus
Limit вроде нельзя использовать HQL

2023-06-09 20:14 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/dao/impl/LayerDaoImpl.java
> +             WHERE l.state IN :layerStatus
верно, limit в Hql нет.

2023-06-10 12:18 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      return List.of(List.of("Такого слоя не существует.  Последний стабильный слой имеет id" + lastStableLayer.getId()));
Поправил

2023-06-10 12:18 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      return List.of(List.of("Тестовый слой унаследован от последнего стабильного слоя. [Сделал тестовый слой с Id" + mergingLayer.getId() + " стабильным]"));
поправил

2023-06-10 12:18 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  public List<List<String>> mergeLayerWithParent(Long layerId) {
поправил

2023-06-12 23:04 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    List<SegmentSelectedDto> selectedDtoList = new ArrayList<>();
Массив можно проинициализировать ниже

2023-06-12 23:04 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (Objects.equals(mergingLayer.getParent().getId(), lastStableLayer.getId()) && mergingLayer.getState() != LayerStateType.CONFLICT) {
А архивный слой можно мержить в основную ветку?

2023-06-12 23:04 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (!checkStateSegment(selectedDtoList) ||
Мне кажется, будет понятнее, если инвертировать логику в методах-проверках и убрать отрицание в условии

2023-06-12 23:04 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  public boolean checkScreenPositionAndState(List<SegmentSelectedDto> selectedDtoList) {
Метод называется checkScreenPositionAndState, но проверяется только position

2023-06-13 08:01 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    List<SegmentSelectedDto> selectedDtoList = new ArrayList<>();
поправил

2023-06-13 08:03 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (Objects.equals(mergingLayer.getParent().getId(), lastStableLayer.getId()) && mergingLayer.getState() != LayerStateType.CONFLICT) {
поправил

2023-06-13 08:04 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  public boolean checkScreenPositionAndState(List<SegmentSelectedDto> selectedDtoList) {
поправил

2023-06-13 08:06 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (!checkStateSegment(selectedDtoList) ||
не совсем понял

2023-06-15 00:23 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  @Transactional
Этот метод вызывается в другом методе, где уже есть @Transactional, по идее тут аннотация не нужна

2023-06-15 00:23 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, SegmentStateLink> margingSegmentStateLinkMap = segmentService.getLatestSSLInSpace(segmentService.getSSLInSpace(List.of(mergingLayer), ""));
Тут проще найти margingSegmentStateLinkMap через dao, как сделано в других методах

2023-06-15 00:23 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, QuestionRequiredLink> parentsQuestionRequiredLinksMap = latestParentsQuestionRequiredLinks
Понимаю, зачем нужна эта конструкция, но выглядит пугающе, конечно) 
Можно обойтись без этого, если в -Latest методах возвращать мапу (и поправить код везде, где сломается при этом). А то иначе получается двойная работа - получили мапу, из нее получили массив, чтобы потом снова собирать мапу

2023-06-15 11:11 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, QuestionRequiredLink> parentsQuestionRequiredLinksMap = latestParentsQuestionRequiredLinks
Очевидно, что можно править методы из segmentservice, но договаривались использовать что есть

2023-06-15 11:11 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, SegmentStateLink> margingSegmentStateLinkMap = segmentService.getLatestSSLInSpace(segmentService.getSSLInSpace(List.of(mergingLayer), ""));
Только вернет он List

2023-06-15 11:38 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, SegmentStateLink> margingSegmentStateLinkMap = segmentService.getLatestSSLInSpace(segmentService.getSSLInSpace(List.of(mergingLayer), ""));
Да, согласен, ты прав

2023-06-15 11:43 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Map<Long, QuestionRequiredLink> parentsQuestionRequiredLinksMap = latestParentsQuestionRequiredLinks
Я не настаиваю) написал в качестве предложения. Если правильно помню, договорились использовать, что есть, но доработать при необходимости

2023-06-15 18:37 UTC, antonpigusov approved these changes

2023-06-15 18:41 UTC, merged