Add force merge
hhru-school/segment-admin-panel pull request #63
Opened 2023-06-12 10:26 UTC by rubikkubika

Добавил ручку для forcemerge если нет конлфиктов

/{layerId}/forcemerge

2023-06-12 23:25 UTC, antonpigusov commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (mergingLayer.getState() == LayerStateType.CONFLICT) {
Я думал, что смысл force merge в том, чтобы сделать merge принудительно, не смотря на то, есть конфликты или нет. Тут получается, что смержим, только если слой неконфликтный, но при обычном merge слой и так автоматически смержится, если конфликтов не будет, т.е. сейчас force merge дублирует обычный merge по логике.

2023-06-13 06:44 UTC, bannovdaniil requested changes

2023-06-13 06:44 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (optionalMergingLayer.isEmpty()) {
всю эту конструкцию 
```
if (optionalMergingLayer.isEmpty()) {
      throw new HttpNotFoundException("Такого слоя не сущестсвует");
    }
    Layer mergingLayer = optionalMergingLayer.get();
```
можно заменить 
orElseThrow

2023-06-13 06:44 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (mergingLayer.getState() == LayerStateType.STABLE) {
А можно ли Форсемердж делать для TEST слоя?

2023-06-13 06:44 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      throw new HttpBadRequestException("Имеются конфликты");
Если слой в состоянии CONFLICT он какраз и может быть ПринудительноВмержен, в коде вижу что если у нас статус CONFLICT то увидим ошибку о конфликтах.

2023-06-13 07:59 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (optionalMergingLayer.isEmpty()) {
поправил

2023-06-13 07:59 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (mergingLayer.getState() == LayerStateType.STABLE) {
Нет. Поправил

2023-06-13 07:59 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +      throw new HttpBadRequestException("Имеются конфликты");
поправил

2023-06-13 13:39 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (mergingLayer.getState() == LayerStateType.STABLE) {
Предлагаю, вместо множества if оставить один, в котором будет проверка только на необходимое состояние. Т.к. если позже появится еще состояния например MERGE или DRAF придется переписывать код.

2023-06-13 16:04 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    if (mergingLayer.getState() == LayerStateType.STABLE) {
ок. поправил

2023-06-14 16:29 UTC, bannovdaniil requested changes
Артём, в алгоритме мерджа не увидел важного действия. Ознакомься пожалуйста внимательно с алгоритмом.

2023-06-14 19:10 UTC, sabkaryan commented
> Артём, в алгоритме мерджа не увидел важного действия. Ознакомься пожалуйста внимательно с алгоритмом.

можешь написать чего не хватает? думаю так будет намного конструктивнее

2023-06-15 09:12 UTC, bannovdaniil commented
> > Артём, в алгоритме мерджа не увидел важного действия. Ознакомься пожалуйста внимательно с алгоритмом.
> 
> можешь написать чего не хватает? думаю так будет намного конструктивнее

желание есть все таки, чтобы Артем ознакомился с алгоритмом, это уже не первая неточность по алгоритму.

![image](https://github.com/hhru-school/segment-admin-panel/assets/96119195/f1e00b06-efc7-4ae6-bc87-1248fb324b8c)

2023-06-15 09:27 UTC, rubikkubika commented
> > > Артём, в алгоритме мерджа не увидел важного действия. Ознакомься пожалуйста внимательно с алгоритмом.
> > 
> > 
> > можешь написать чего не хватает? думаю так будет намного конструктивнее
> 
> желание есть все таки, чтобы Артем ознакомился с алгоритмом, это уже не первая неточность по алгоритму.
> 
> ![image](https://user-images.githubusercontent.com/96119195/246059426-f1e00b06-efc7-4ae6-bc87-1248fb324b8c.png)

А ничего что установка времени есть в самом сеттер у сущности?

![image](https://github.com/hhru-school/segment-admin-panel/assets/98896050/114967fc-ee86-4e1b-a143-2d2c065ceaab)

2023-06-15 09:53 UTC, bannovdaniil requested changes

2023-06-15 09:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Layer mergingLayer = layerDao.findById(layerId)
Отсутствует проверка, на то, что родитель является последним стабильным.
Отсутствует установка даты стабильности. (в git изменениях) в любом случаи идет нарушение приципа SOLID, что затрудняет как отладку, так и поддержание кода.

2023-06-15 09:53 UTC, bannovdaniil commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +  public MergeResponseDto mergeLayerWithParent(Long layerId) {
ПР только про фрсе мердж? Присутствует код который не относится к этому.

2023-06-15 10:19 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Layer mergingLayer = layerDao.findById(layerId)
Во первых логика внесение даты в базу была зафиксирована в переписке.

Во вторых кто то это точно видел.

В третьих если бы ты нормально написал в чем проблема, я бы подсветил и если уж такая большая критичность то это можно было поправить, сложности нет.

Однако, с твоим деструктивным подходом довольно сложно придти к результату

2023-06-15 11:18 UTC, rubikkubika commented on src/main/java/ru/hhschool/segment/service/LayerService.java
> +    Layer mergingLayer = layerDao.findById(layerId)
Для справки третье мнение
![image](https://github.com/hhru-school/segment-admin-panel/assets/98896050/69fb3bb1-0f85-4dd7-8bf9-a9230b0992e9)

2023-06-16 08:26 UTC, closed without merging